AWSTemplateFormatVersion: "2010-09-09"

Description: This template provides a ELB, autoscaling, ec2 and dynamoDB

Resources:
  IAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: lambda-db-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:PutItem'
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:Scan'
                  - 'dynamodb:Query'
                  - 'dynamodb:UpdateItem'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 's3:Put*'
                  - 's3:Get*'
                Resource:
                  - arn:aws:s3:::lambda-bodies-s3
                  - arn:aws:s3:::lambda-bodies-s3/*
              - Effect: Allow
                Action:
                  - 'logs:CreateLogStream'
                  - 'logs:CreateLogGroup'
                  - 'logs:PutLogEvents'
                Resource: '*'
  DNAResultsTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "Id"
          AttributeType: "S"
      BillingMode: "PAY_PER_REQUEST"
      KeySchema: 
        - 
          AttributeName: "Id"
          KeyType: "HASH"
      TableName: "dna-results"
      Tags: 
        - 
          Key: "type"
          Value: "xmen"
    DependsOn:
      - IAMRole


  # IsMutantLambdaFunction:
  #   Type: 'AWS::Lambda::Function'
  #   Properties:
  #     Code:
  #       S3Bucket: "lambda-bodies-s3"
  #       S3Key: "lambdas.zip"        
  #     FunctionName: "is-mutant-lambda-function"
  #     Handler: is-mutant-lambda.handler
  #     Runtime: nodejs12.x
  #     Role: !GetAtt IAMRole.Arn
  #   DependsOn:
  #     - DNAResultsTable
  #     - IAMRole

  # MutantsApi:
  #   Type: AWS::ApiGatewayV2::Api
  #   Properties: 
  #     # BasePath: String
  #     # Body: Json
  #     # BodyS3Location: 
  #     #   BodyS3Location
  #     CorsConfiguration: 
  #       AllowCredentials: true
  #       AllowHeaders: 
  #         - String
  #       AllowMethods: 
  #         - 
  #           'GET'
  #           'POST'
  #           'OPTIONS'
  #       AllowOrigins: 
  #         - String
  #       ExposeHeaders: 
  #         - String
  #       MaxAge: Integer
  #     Description: "Api for mutants stufs"
  #     Name: "mutants-api"
  #     ProtocolType: "HTTP"
  #     Target: String
  #     Version: String


